// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimeiraApi.Data;

#nullable disable

namespace PrimeiraApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PrimeiraApi.Models.Categoria", b =>
                {
                    b.Property<int>("Cat_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Cat_Id"));

                    b.Property<string>("Cat_Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Cat_PaiId")
                        .HasColumnType("int");

                    b.HasKey("Cat_Id");

                    b.HasIndex("Cat_PaiId");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("PrimeiraApi.Models.Produto", b =>
                {
                    b.Property<int>("Pd_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Pd_Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Pd_Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Pd_ImagenUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Pd_Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Pd_Preco")
                        .HasColumnType("int");

                    b.Property<int>("Pd_Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Pd_Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("PrimeiraApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PrimeiraApi.Models.Categoria", b =>
                {
                    b.HasOne("PrimeiraApi.Models.Categoria", "CategoriaPai")
                        .WithMany("SubCategotia")
                        .HasForeignKey("Cat_PaiId");

                    b.Navigation("CategoriaPai");
                });

            modelBuilder.Entity("PrimeiraApi.Models.Produto", b =>
                {
                    b.HasOne("PrimeiraApi.Models.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("PrimeiraApi.Models.Categoria", b =>
                {
                    b.Navigation("Produtos");

                    b.Navigation("SubCategotia");
                });
#pragma warning restore 612, 618
        }
    }
}
